{{- if .Values.networkPolicies.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      release: {{ .Release.Name }}
  ingress:
  - from:
    - namespaceSelector:
      matchLabels:
        release: {{ .Release.Name }}
{{- end }}
