{{- if .Values.networkPolicies.enable }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "connectivity-intake.labels" . | indent 4}}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  ingress:
  - from:
    - podSelector:
      matchLabels:
        release: {{ .Release.Name }}
    - podSelector:
      matchLabels:
        app.kubernetes.io/name: {{ .Values.name }}
{{- end }}
