{{- $sessionSecret := (randAlphaNum 32) | b64enc | quote }}
{{- $dbAppPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $dbOwnerPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $dbReadonlyPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print (include "connectivity-intake.fullname" .) }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- if index $secret.data "session-secret" }}{{- $sessionSecret = index $secret.data "session-secret" }}{{- end -}}
{{- if index $secret.data "database-app-password" }}{{- $dbAppPassword = index $secret.data "database-app-password" }}{{- end -}}
{{- if index $secret.data "database-owner-password" }}{{- $dbOwnerPassword = index $secret.data "database-owner-password" }}{{- end -}}
{{- if index $secret.data "database-readonly-password" }}{{- $dbReadonlyPassword = index $secret.data "database-readonly-password" }}{{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: 
{{ include "connectivity-intake.labels" . | indent 4}}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  session-secret: {{ $sessionSecret }}
  database-name: {{ .Values.db.name | b64enc | quote }}
  database-owner-user: {{ .Values.db.ownerUser | b64enc | quote }}
  database-owner-password: {{ $dbOwnerPassword }}
  database-app-user: {{ .Values.db.appUser | b64enc | quote }}
  database-app-password: {{ $dbAppPassword }}
  database-readonly-user: {{ .Values.db.readonlyUser | b64enc | quote }}
  database-readonly-password: {{ $dbReadonlyPassword }}
