apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "connectivity-intake.labels" . | indent 4}}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: {{ .Values.name }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - status: 'True'
      type: Admitted
    host: {{ .Values.route.host }}
    routerName: router
    wildcardPolicy: None
