apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
{{ include "connectivity-intake.labels" . | indent 4}}
spec:
  ports:
  - name: {{ .Values.name }}
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    component: app
  sessionAffinity: None
  type: ClusterIP
