apiVersion: v1
kind: Secret
metadata:
  name: sso-express
  labels: 
{{ include "connectivity-intake.labels" . | indent 4}}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
type: Opaque
data:
  client-secret: {{ .Values.image.app.clientSecret | b64enc | quote }}
