apiVersion: v2
name: connectivity-intake
description: A Helm chart for the Connectivity Intake
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: spilo
    version: 0.2.0
    repository: https://bcgov.github.io/spilo-chart
  - name: cas-metabase
    version: 0.12.1
    repository: https://bcgov.github.io/cas-metabase/
