{{ if .Values.deployer.serviceAccount.enabled }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-deployer
  labels:
{{ include "connectivity-intake.labels" . | indent 4}}
  namespace: {{ .Values.deployer.namespace }}

{{ end }}
