kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-metabase-access
  labels:
{{ include "connectivity-intake.labels" . | indent 4}}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}-spilo
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Values.metabase.namespace }}
      podSelector:
        matchLabels:
          app.kubernetes.io/instance: {{ .Values.metabase.instanceName }}
