fullnameOverride: connectivity-intake
replicaCount: 3
defaultImagePullPolicy: IfNotPresent
defaultImageTag: latest

image:
  app:
    repository: ghcr.io/bcgov/connectivity-intake/connectivity-intake-app
    pullPolicy: IfNotPresent
    tag: latest # The tag value must be passed in via the deploy script
    clientSecret: "" # clientSecret must be passed in via deploy script
  psql:
    repository: gcr.io/ggl-cas-storage/cas-postgres
    tag: "0.3.0"
  db:
    repository: ghcr.io/bcgov/connectivity-intake/connectivity-intake-db
    pullPolicy: IfNotPresent
    tag: latest # The tag value must be passed in via the deploy script
app:
  port: "3000"
  probesPort: "9000"
  namespace: ""
route:
  host: ""  # The host value must be passed in via the deploy script: connectivity-rtp.apps.silver.devops.gov.bc.ca

networkPolicies:
  enabled: true

resources:
  app:
    requests: 
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "150m"
      memory: "256Mi"
  psql:
    limits:
      cpu: "150m"
      memory: "64Mi"
    requests:
      cpu: "50m"
      memory: "32Mi"

deployer:
  namespace: bc5936-dev
  serviceAccount:
    enabled: true

db:
  name: connectivity_intake
  appUser: connectivity_intake_app
  ownerUser: connectivity_intake
  preInitCommand: ""

continuousArchive:
  # Specifies whether continuous archiving with wal-g should be enabled
  enabled: true
  # Cron schedule for doing base backups
  scheduleCronJob: 00 01 * * *
  # Amount of base backups to retain
  retainBackups: 15

  # The storage solution used by wal-g: pvc (default), s3, or gcs are supported by this helm chart
  # https://github.com/wal-g/wal-g/blob/master/docs/STORAGES.md
  storage: pvc
  pvc:
    storageClass: netapp-file-backup
    size: 500Mi

  s3:
    bucket: ~
    secretName: ~
  gcs:
    bucket: ~
    # The GCS  bucket folder where the logs will be updated
    backupLocation: wal
    # Name of the secret that holds the credentials to the bucket
    credentialSecretName: ~

persistentVolume:
  enabled: true
  size: 250Mi
  storageClass: "netapp-block-standard"
  subPath: ""
  mountPath: "/home/postgres/pgdata"
  annotations: {}
  accessModes:
    - ReadWriteOnce
