name: connectivity-intake
replicaCount: 3

image:
  app:
    repository: ghcr.io/bcgov/connectivity-intake
    pullPolicy: IfNotPresent
    # The tag value must be passed in via the deploy script
    tag: latest
port: "3000"
route:
  host: connectivity-intake-dev.apps.silver.devops.gov.bc.ca

networkPolicies:
  enabled: true

resources:
  app:
    requests: 
      cpu: "80m"
      memory: "150Mi"
    limits:
      cpu: "160m"
      memory: "300Mi"

deployer:
  namespace: bc5936-dev
  serviceAccount:
    enabled: true

cas-postgres:
  patroni:
    resources:
      limits:
        cpu: "15m"
        memory: "100Mi"
      requests:
        cpu: "15m"
        memory: "100Mi"
    persistentVolume:
      size: 1Mi
      storageClass: netapp-block-standard
    replicaCount: 3
    env:
      ALLOW_NOSSL: true
      USE_WALG_BACKUP: "true"
      USE_WALG_RESTORE: "true"
    walE:
      enable: false # to be changed when we do backups
      gcsBucket: ~
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: ~
    # options below are required if walE.enable is true
  namespace: ~
  gcs:
    bucketSuffix: ~
