fullnameOverride: connectivity-intake
replicaCount: 3
defaultImagePullPolicy: IfNotPresent
defaultImageTag: latest

image:
  app:
    repository: ghcr.io/bcgov/connectivity-intake/connectivity-intake-app
    pullPolicy: IfNotPresent
    tag: latest # The tag value must be passed in via the deploy script
  psql:
    repository: gcr.io/ggl-cas-storage/cas-postgres
    tag: "0.3.0"
  db:
    repository: ghcr.io/bcgov/connectivity-intake/connectivity-intake-db
    pullPolicy: IfNotPresent
    tag: latest # The tag value must be passed in via the deploy script 
port: "3000"
route:
  host: connectivity-intake-dev.apps.silver.devops.gov.bc.ca

networkPolicies:
  enabled: true

resources:
  app:
    requests: 
      cpu: "70m"
      memory: "256Mi"
    limits:
      cpu: "210m"
      memory: "512Mi"

deployer:
  namespace: bc5936-dev
  serviceAccount:
    enabled: true

cas-postgres:
  patroni:
    resources:
      limits:
        cpu: "210m"
        memory: "512Mi"
      requests:
        cpu: "70m"
        memory: "256Mi"
    persistentVolume:
      size: "300Mi"
      storageClass: netapp-block-standard
    replicaCount: 3
    env:
      ALLOW_NOSSL: true
      USE_WALG_BACKUP: "true"
      USE_WALG_RESTORE: "true"
    walE:
      enable: false # to be changed when we do backups
      gcsBucket: ~
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: ~
    # options below are required if walE.enable is true
  namespace: ~
  gcs:
    bucketSuffix: ~

db:
  name: connectivity_intake
  appUser: connectivity_intake_app
  ownerUser: connectivity_intake
  preInitCommand: ""
