fullnameOverride: connectivity-intake
replicaCount: 3
defaultImagePullPolicy: IfNotPresent
defaultImageTag: latest

image:
  app:
    repository: ghcr.io/bcgov/connectivity-intake/connectivity-intake-app
    pullPolicy: IfNotPresent
    tag: latest # The tag value must be passed in via the deploy script
    clientSecret: "" # clientSecret must be passed in via deploy script
  psql:
    repository: gcr.io/ggl-cas-storage/cas-postgres
    tag: "0.3.0"
  db:
    repository: ghcr.io/bcgov/connectivity-intake/connectivity-intake-db
    pullPolicy: IfNotPresent
    tag: latest # The tag value must be passed in via the deploy script
app:
  port: "3000"
  probesPort: "9000"
  namespace: ""
route:
  host: ""  # The host value must be passed in via the deploy script: connectivity-rtp-dev.apps.silver.devops.gov.bc.ca

networkPolicies:
  enabled: true

resources:
  app:
    requests: 
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "150m"
      memory: "256Mi"

deployer:
  namespace: bc5936-dev
  serviceAccount:
    enabled: true

spilo:
  resources:
    limits:
      cpu: "50m"
      memory: "64Mi"
    requests:
      cpu: "10m"
      memory: "32Mi"
  persistentVolume:
    size: "250Mi"
  pvc:
    size: "500Mi"

db:
  name: connectivity_intake
  appUser: connectivity_intake_app
  ownerUser: connectivity_intake
  preInitCommand: ""
