name: Deploy application tools

on:
  push
    # branches: [main]

jobs:
  deploy-tools:
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy sysdig
        run: |
          chmod +x ./lib/tools_deploy.sh
          ./lib/tools_deploy.sh -n ${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}
