name: Postgres tests with pg-tap

on:
  pull_request:
    branches: [ main ]

env:
  PGPASSWORD: postgres
  PGUSER: postgres
  PGDATABASE: connectivity_intake
  PGHOST: postgres

jobs:
  pgTAP-tests:
    runs-on: ubuntu-latest
    container: 
      image: node:16
    services: 
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_DB: ${{ env.PGDATABASE }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: install sudo
        run: apt update && apt install sudo -y
      - name: install pg_prove
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: install postgres and sqitch
        run: sudo apt-get install -y --no-install-recommends postgresql-server-dev-all postgresql-client sqitch libdbd-pg-perl;
      - name: provision database
        working-directory: db
        run: sqitch deploy -h ${{ env.PGHOST }};
        env:
          SHELL: /bin/bash
      # - name: Checkout pgtap
      #   uses: actions/checkout@v2
      #   with:
      #     repository: theory/pgtap
      #     path: pgtap
      #     ref: v1.2.0
      # - name: install pgtap
      #   working-directory: pgtap
      #   run: make
      - name: install pgtap
        run: make && psql -d connectivity_intake -c 'CREATE EXTENSION IF NOT EXISTS pgtap;'
      - name: Run tests
        run: PGPASSWORD=${{ env.PGPASSWORD }} pg_prove --host ${{ env.PGHOST }} --port ${{ job.services.postgres.ports[5432] }} --username ${{ env.PGUSER }} --dbname ${{ env.PGDATABASE }} app/pgTap/*_test.sql
