name: Postgres tests with pg-tap

on:
  pull_request:
    branches: [ main ]

env:
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: connectivity_intake

jobs:
  pgTAP-tests:
    runs-on: ubuntu-latest
    container: 
      image: node:16
    services: 
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: install sudo
        run: apt update && apt install sudo -y
      - name: install pg_prove
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: install postgres dev
        run: sudo apt-get install -y --no-install-recommends postgresql-server-dev-all && sudo apt-get install postgresql-client
      - name: Checkout pgtap
        uses: actions/checkout@v2
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.2.0
      - name: install pgtap
        working-directory: pgtap
        run: make && psql --host localhost --username ${{ env.POSTGRES_USER }} --dbname ${{ env.POSTGRES_DB }} --file sql/pgtap.sql
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
      - name: Provision database
        working-directory: db
        run: sqitch deploy
      - name: Run tests
        run: pg_prove --host localhost --username ${{ env.POSTGRES_USER }} --dbname ${{ env.POSTGRES_DB }} app/pgTap/*_test.sql
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
