name: Postgres tests with pg-tap

on:
  [workflow_call]

env:
  PGPASSWORD: postgres
  PGUSER: postgres
  PGDATABASE: connectivity_intake

jobs:
  pgtap-tests:
    name: pgtap-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - name: Setup Postgres DB
        run: |
          sudo apt-get update
          sudo apt-get install -yqq sqitch libdbd-pg-perl postgresql-client
          asdf plugin-add postgres || true
          asdf plugin-update --all
          asdf install postgres 14.1
          asdf reshim
          pg_ctl start
          createdb ${{ env.PGDATABASE }}
          sqitch deploy
        working-directory: ./db
      - name: Install pg_prove
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: Install pgtap
        run: |
          git clone https://github.com/theory/pgtap.git
          cd pgtap
          git checkout v1.1.0
          git branch
          make
          make install
          psql -c 'CREATE EXTENSION pgtap;'
      - name: Run Tests
        run: pg_prove --username ${{ env.PGUSER }} --dbname ${{ env.PGDATABASE }} app/pgTap/*_test.sql
